var _ScriptThemeCongif_ = {};
_ScriptThemeCongif_.setting_fonts = "HLTAparo=HLTAparo;\
HLT AphroditeSlimPro=HLTAphroditeSlimPro;\
HLT Affair=HLTAffair;\
FS Maksim=FSMaksim;\
Grey Wolf=GreyWolf;\
Captain Podd=CaptainPodd;\
DVF Siam=DVFSiam;\
HLT AphroditeSlimStylistic=HLTAphroditeSlimStylistic;\
Baby Doodles=BabyDoodles;\
Desire=Desire;\
ByTheButterfly=ByTheButterfly;\
HLT Festival Scrip tPro=HLTFestivalScriptPro;\
HLT Society=HLTSociety;\
HLT Jojo=HLTJojo;\
HLT Fall For You=HLTFallForYou;\
HLT Giddyup Std=HLTGiddyupStd;\
HLT Mirella Script Limited=HLTMirellaScriptLimited;\
HLT Sudestada=HLTSudestada;\
HLT Narziss Swirls=HLTNarzissSwirls;\
HLT Mishka=HLTMishka;\
HLT Carpenter Script=HLTCarpenterScript;\
HLT LookUp=HLTLookUp;\
HLT Sail Away=HLTSailAway;\
HLT Burgues Script=HLTBurguesScript;\
HLT Motion Picture=HLTMotionPicture;\
Jellyka End_less Voyage=JellykaEndlessVoyage;\
HLT Fitigraf S=HLTFitigraf-S;\
Jellyka CuttyCupcakes=JellykaCuttyCupcakes;\
HLT Sneaker Script=HLTSneakerScript;\
HLT Geotica 2012=HLTGeotica2012;\
Jellyka Delicious Cake=JellykaDeliciousCake;\
HLT Finura Roman=HLTFinuraRoman;\
HLT Red Wagon Stylistic=HLTRedWagonStylistic;\
HLT Buttermilk=HLTButtermilk;\
HLT CL MissLeGatees1=HLTCLMissLeGatees1;\
Jellyka BeesAntique Handwriting=JellykaBeesAntiqueHandwriting;\
HLT Pepita Script=HLTPepitaScript;\
HLT JaneAusten NoSecret=HLTOlivertuelesfourmis;\
HLT Vindeco=HLTVindeco;\
HLT Elisa=HLTElisa;\
HLT Suave Script=HLTSuaveScript;\
HLT Stringbead=HLTStringbead;\
HLT Windsong=HLTWindsong;\
HLT FoglihtenNo04=HLTFoglihtenNo04;\
HLT Signerica Medium=HLTSignericaMedium;\
UVF Channel=UVFChannel;\
SirQuitry=SirQuitry;\
Jellyka - le Grand Saut=Jellyka-leGrandSaut;\
Peake=Peake;\
UVF Cider Script=UVFCiderScript;\
Jellyka Gare de Chambord=JellykaGaredeChambord;\
UVF Aleo=UVFAleo;\
Jellyka Waterways Seafarers=JellykaWaterwaysSeafarers;\
UVF Before the Rain=UVFBeforetheRain;\
UVF Aphrodite Pro=UVFAphroditePro;\
Jellyka Western Princess=JellykaWesternPrincess;\
ThuphapXuan=ThuphapXuan;\
UVF Buttermilk=UVFButtermilk;\
UVF Bilancio alternate=UVFBilancioalternate;\
UVF A Charming Font Expanded=UVFACharmingFontExpanded;\
jey=jey;\
UVF Austie Bost Blueberry Muffins=UVFBlueberryMuffins;\
Jellyka King's Hat=JellykaKing'sHat;\
Jellyka Lucky Day=JellykaLuckyDay;\
UVF Aquus=UVFAquus-Regular;\
RixLoveFool=RixLoveFool;\
Jellyka Castle's Queen=Dunno;\
Jellyka Saint-Andrew's Queen=JellykaSaint-AndrewsQueen;\
Rock Show Whiplash=RockShowWhiplash;\
UVF Chopin Script=UVFChopinScript;\
Jellyka - Estrya's Handwriting=Jellyka-Estrya'sHandwriting;\
Jellyka Wonderland Wine=JellykaWonderlandWine;\
Jellyka - Nathaniel a Mystery=Jellyka-NathanielaMystery;\
OctemberScriptVi=OctemberScriptVi;\
StelaUT VH=StelaUTVH;\
Teitheas=Teitheas;\
Shelia VNF=SheliaVNF;\
UVF Call Me Maybe=UVFCallMeMaybe;\
Jellyka - Love and Passion=Jellyka-LoveandPassion;\
UVF Chikita=UVFChikita;\
Jellyka - le Grand Saut Textual=Jellyka-leGrandSautTextual;\
UVF Bariol Regular Italic=UVFBariolRegular-Italic;\
Rose=Rose;\
UVF Bird Script Pro=UVFBirdScriptPro;\
Paris Bold Strip=Paris-BoldStrip;\
Jellyka - Love and Passion=Jellyka-LoveandPassion;\
Platinus Script Pro=UVFBallantinesScriptEF;\
UVF BallantinesScriptEF=Desire;\
UVF Ambassador=UVFAmbassador;\
Paris Pro Regular Exit=ParisPro-RegularExit;\
UVF Amplify=UVFAmplify;\
UVF Barmbrack=UVFBarmbrack;\
Paris=Paris;\
UVF Bookeyed Jack=UVFBookeyedJack;\
Mussica=Mussica;\
UVF Brand Pro=UVFBrandPro;\
Mussica Swash=MussicaSwash;\
UVF Breathe Pro=UVFBreathePro;\
UVF Mandevilla=UVFHelveticaNeue-Roman;\
UVF Helvetica 55 Roman=UVFHelveticaNeue-Roman;\
UVF Cupid de Locke=UVFCupiddeLocke;\
UVF Ithornet=UVFIthornet;\
UVF Futura LT=UVFFuturaLT;\
UVF Jellyka Endless Voyage=UVFJellykaEndlessVoyage;\
UVF Didot LT Std Italic=UVFDidotLTStd-Italic;\
UVF Memoriam Pro=UVFMemoriamPro;\
UVF EloquentJF Swash=UVFEloquentJFSwash;\
UVF Kewl Script=UVFKewlScript;\
UVF DaddysGirl=UVFDaddysGirl;\
UVF Corinthia=UVFCorinthia;\
UVF Kaileen=UVF Kaileen;\
UVF Funkydori=UVFFunkydori;\
UVFDartangnonStd=UVFDartangnonStd;\
UVF LoveStory=UVFLoveStory;\
UVF Lavanderia Regular=UVFLavanderiaRegular;\
UVF LP Bambus Light=UVFLPBambusLight;\
Harbell Personal Use Only=HarbellPersonalUseOnly;\
UVF Geotica=UVFGeotica;\
UVF Little Days=UVFLittleDays;\
UVF Dartangnon Std=UVFDartangnonStd;\
UVF Legendaria=UVFLegendaria;\
UVF Memoir=UVFMemoir;\
UVF Filmotype Honey=UVFFilmotypeHoney;\
UVF Dartangnon Std=UVFDartangnonStd;\
Frosting for Breakfast=FrostingforBreakfast;\
UVF Gulyesa Script=UVFGulyesaScript;\
UVF Connie=UVFConnie;\
UVF Legendaria Swashes 1=UVFLegendariaSwashes1;";